execute: 
  freeze: auto
project:
  resources:
    - "Resources"
    - "Hal_css.css"
    - "Hal_css_dark.css"
    - "custom_hal.js"
  type: website
  output-dir: public
website:
  title: "Théodore Cherrière"
  #image: avatar.jpg
  #favicon: avatar.jpg
  description: "Théodore Cherrière's personal webpage"
  site-url: https://tcherrie.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: news.qmd
        text: News
     # - href: Resources/chemin_pdf
     #   text: le nom cliquable sur le site
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Webinar incoming** - 2024-11-06 : [IEEE Magnetic Society webinar](https://x.com/IEEEMagSoc/status/1836374722906386598) "
    type: light
    position: below-navbar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



