execute: 
  freeze: auto
project:
  resources:
    - "Resources"
    - "Hal_css.css"
    - "Hal_css_dark.css"
    - "custom_hal.js"
    - "googlea2b49b9b8a1e1325.html"
  type: website
  output-dir: public
website:
  title: "Théodore Cherrière"
  #image: avatar.jpg
  #favicon: avatar.jpg
  description: "Théodore Cherrière's personal webpage"
  site-url: https://tcherrie.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: news.qmd
        text: News
      - href: Resources/CV_website.pdf
        text: CV
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**RICAM Special Semester ** - October 27-31, Linz : [Workshop on Advanced techniques for design optimization in engineering applications](https://www.ricam.oeaw.ac.at/specsem/specsem2025/workshop2/)"
    type: light
    position: below-navbar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



