execute: 
  freeze: auto
project:
  resources:
    - "Resources"
    - "Hal_css.css"
    - "Hal_css_dark.css"
    - "custom_hal.js"
    - "googlea2b49b9b8a1e1325.html"
  type: website
  output-dir: public
website:
  title: "Théodore Cherrière"
  #image: avatar.jpg
  #favicon: avatar.jpg
  description: "Théodore Cherrière's personal webpage"
  site-url: https://tcherrie.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: news.qmd
        text: News
     # - href: Resources/chemin_pdf
     #   text: le nom cliquable sur le site
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Internship offers available** - [Strudy of a new flux-switching machine](/posts/2024/2024-11-07_internship_SATIE_FluxSwitching/index.qmd), [Implementation of FEM on interpretable NN](/posts/2024/2024-11-06_internship_LMS_HiDENN-FEM/index.qmd)"
    type: light
    position: below-navbar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



